//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopingCar.Web.ShoppingCarServer {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ShoppingCarServer.IShoppingServer")]
    public interface IShoppingServer {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingServer/CrearProducto", ReplyAction="http://tempuri.org/IShoppingServer/CrearProductoResponse")]
        ShopingCar.Server.wsSQLResult CrearProducto(System.IO.Stream JSONdataStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingServer/CrearProducto", ReplyAction="http://tempuri.org/IShoppingServer/CrearProductoResponse")]
        System.Threading.Tasks.Task<ShopingCar.Server.wsSQLResult> CrearProductoAsync(System.IO.Stream JSONdataStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingServer/BuscarProductoNombre", ReplyAction="http://tempuri.org/IShoppingServer/BuscarProductoNombreResponse")]
        ShopingCar.Server.Producto_[] BuscarProductoNombre(System.IO.Stream JSONdataStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingServer/BuscarProductoNombre", ReplyAction="http://tempuri.org/IShoppingServer/BuscarProductoNombreResponse")]
        System.Threading.Tasks.Task<ShopingCar.Server.Producto_[]> BuscarProductoNombreAsync(System.IO.Stream JSONdataStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingServer/CrearPedido", ReplyAction="http://tempuri.org/IShoppingServer/CrearPedidoResponse")]
        ShopingCar.Server.wsSQLResult CrearPedido(System.IO.Stream JSONdataStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingServer/CrearPedido", ReplyAction="http://tempuri.org/IShoppingServer/CrearPedidoResponse")]
        System.Threading.Tasks.Task<ShopingCar.Server.wsSQLResult> CrearPedidoAsync(System.IO.Stream JSONdataStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingServer/CrearUsuario", ReplyAction="http://tempuri.org/IShoppingServer/CrearUsuarioResponse")]
        ShopingCar.Server.wsSQLResult CrearUsuario(System.IO.Stream JSONdataStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingServer/CrearUsuario", ReplyAction="http://tempuri.org/IShoppingServer/CrearUsuarioResponse")]
        System.Threading.Tasks.Task<ShopingCar.Server.wsSQLResult> CrearUsuarioAsync(System.IO.Stream JSONdataStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingServer/HacerPedido", ReplyAction="http://tempuri.org/IShoppingServer/HacerPedidoResponse")]
        ShopingCar.Server.wsSQLResult HacerPedido(System.IO.Stream JSONdataStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingServer/HacerPedido", ReplyAction="http://tempuri.org/IShoppingServer/HacerPedidoResponse")]
        System.Threading.Tasks.Task<ShopingCar.Server.wsSQLResult> HacerPedidoAsync(System.IO.Stream JSONdataStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingServer/LoginUsuario", ReplyAction="http://tempuri.org/IShoppingServer/LoginUsuarioResponse")]
        ShopingCar.Server.wsSQLResult LoginUsuario(System.IO.Stream JSONdataStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingServer/LoginUsuario", ReplyAction="http://tempuri.org/IShoppingServer/LoginUsuarioResponse")]
        System.Threading.Tasks.Task<ShopingCar.Server.wsSQLResult> LoginUsuarioAsync(System.IO.Stream JSONdataStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingServer/ListarDetalle", ReplyAction="http://tempuri.org/IShoppingServer/ListarDetalleResponse")]
        ShopingCar.Server.DetallePedido_[] ListarDetalle(System.IO.Stream JSONdataStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingServer/ListarDetalle", ReplyAction="http://tempuri.org/IShoppingServer/ListarDetalleResponse")]
        System.Threading.Tasks.Task<ShopingCar.Server.DetallePedido_[]> ListarDetalleAsync(System.IO.Stream JSONdataStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingServer/ListarPedidos", ReplyAction="http://tempuri.org/IShoppingServer/ListarPedidosResponse")]
        ShopingCar.Server.Pedido_[] ListarPedidos(System.IO.Stream JSONdataStream);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IShoppingServer/ListarPedidos", ReplyAction="http://tempuri.org/IShoppingServer/ListarPedidosResponse")]
        System.Threading.Tasks.Task<ShopingCar.Server.Pedido_[]> ListarPedidosAsync(System.IO.Stream JSONdataStream);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IShoppingServerChannel : ShopingCar.Web.ShoppingCarServer.IShoppingServer, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShoppingServerClient : System.ServiceModel.ClientBase<ShopingCar.Web.ShoppingCarServer.IShoppingServer>, ShopingCar.Web.ShoppingCarServer.IShoppingServer {
        
        public ShoppingServerClient() {
        }
        
        public ShoppingServerClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShoppingServerClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShoppingServerClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShoppingServerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ShopingCar.Server.wsSQLResult CrearProducto(System.IO.Stream JSONdataStream) {
            return base.Channel.CrearProducto(JSONdataStream);
        }
        
        public System.Threading.Tasks.Task<ShopingCar.Server.wsSQLResult> CrearProductoAsync(System.IO.Stream JSONdataStream) {
            return base.Channel.CrearProductoAsync(JSONdataStream);
        }
        
        public ShopingCar.Server.Producto_[] BuscarProductoNombre(System.IO.Stream JSONdataStream) {
            return base.Channel.BuscarProductoNombre(JSONdataStream);
        }
        
        public System.Threading.Tasks.Task<ShopingCar.Server.Producto_[]> BuscarProductoNombreAsync(System.IO.Stream JSONdataStream) {
            return base.Channel.BuscarProductoNombreAsync(JSONdataStream);
        }
        
        public ShopingCar.Server.wsSQLResult CrearPedido(System.IO.Stream JSONdataStream) {
            return base.Channel.CrearPedido(JSONdataStream);
        }
        
        public System.Threading.Tasks.Task<ShopingCar.Server.wsSQLResult> CrearPedidoAsync(System.IO.Stream JSONdataStream) {
            return base.Channel.CrearPedidoAsync(JSONdataStream);
        }
        
        public ShopingCar.Server.wsSQLResult CrearUsuario(System.IO.Stream JSONdataStream) {
            return base.Channel.CrearUsuario(JSONdataStream);
        }
        
        public System.Threading.Tasks.Task<ShopingCar.Server.wsSQLResult> CrearUsuarioAsync(System.IO.Stream JSONdataStream) {
            return base.Channel.CrearUsuarioAsync(JSONdataStream);
        }
        
        public ShopingCar.Server.wsSQLResult HacerPedido(System.IO.Stream JSONdataStream) {
            return base.Channel.HacerPedido(JSONdataStream);
        }
        
        public System.Threading.Tasks.Task<ShopingCar.Server.wsSQLResult> HacerPedidoAsync(System.IO.Stream JSONdataStream) {
            return base.Channel.HacerPedidoAsync(JSONdataStream);
        }
        
        public ShopingCar.Server.wsSQLResult LoginUsuario(System.IO.Stream JSONdataStream) {
            return base.Channel.LoginUsuario(JSONdataStream);
        }
        
        public System.Threading.Tasks.Task<ShopingCar.Server.wsSQLResult> LoginUsuarioAsync(System.IO.Stream JSONdataStream) {
            return base.Channel.LoginUsuarioAsync(JSONdataStream);
        }
        
        public ShopingCar.Server.DetallePedido_[] ListarDetalle(System.IO.Stream JSONdataStream) {
            return base.Channel.ListarDetalle(JSONdataStream);
        }
        
        public System.Threading.Tasks.Task<ShopingCar.Server.DetallePedido_[]> ListarDetalleAsync(System.IO.Stream JSONdataStream) {
            return base.Channel.ListarDetalleAsync(JSONdataStream);
        }
        
        public ShopingCar.Server.Pedido_[] ListarPedidos(System.IO.Stream JSONdataStream) {
            return base.Channel.ListarPedidos(JSONdataStream);
        }
        
        public System.Threading.Tasks.Task<ShopingCar.Server.Pedido_[]> ListarPedidosAsync(System.IO.Stream JSONdataStream) {
            return base.Channel.ListarPedidosAsync(JSONdataStream);
        }
    }
}
